# A small starter glossary. You can expand this file gradually.
STARTER_GLOSSARY = {
    "dental caries": {
        "zh": "龋病",
        "definition": "A biofilm-mediated, sugar-driven, multifactorial disease causing mineral loss in dental hard tissues.",
        "explanation_zh": "龋病是一种由生物膜介导、糖驱动的多因素疾病，会导致牙釉质和牙本质脱矿。",
        "category": "Dentistry / Cariology",
    },
    "caries": {
        "zh": "龋病",
        "definition": "A disease process that causes demineralization and destruction of dental hard tissues.",
        "explanation_zh": "龋病是牙体硬组织发生脱矿和破坏的疾病过程，常与牙菌斑和糖摄入有关。",
        "category": "Dentistry / Cariology",
    },
    "biofilm": {
        "zh": "生物膜",
        "definition": "A structured community of microorganisms attached to a surface.",
        "explanation_zh": "生物膜是附着在表面的微生物群落。牙菌斑就是口腔中的典型生物膜。",
        "category": "Microbiology / Dentistry",
    },
    "plaque": {
        "zh": "牙菌斑",
        "definition": "A microbial biofilm attached to the tooth surface.",
        "explanation_zh": "牙菌斑是附着在牙面上的微生物生物膜，是龋病和牙周病的重要致病因素。",
        "category": "Preventive Dentistry",
    },
    "calculus": {
        "zh": "牙结石",
        "definition": "Mineralized dental plaque.",
        "explanation_zh": "牙结石是矿化后的牙菌斑，常刺激牙龈并加重牙周炎症。",
        "category": "Periodontology",
    },
    "demineralization": {
        "zh": "脱矿",
        "definition": "Loss of minerals from dental hard tissues.",
        "explanation_zh": "脱矿是牙釉质或牙本质中的矿物质流失，是龋病形成的重要过程。",
        "category": "Cariology",
    },
    "remineralization": {
        "zh": "再矿化",
        "definition": "Restoration of minerals into dental hard tissues.",
        "explanation_zh": "再矿化是矿物质重新沉积到牙体硬组织中的过程，可帮助早期龋损修复。",
        "category": "Cariology",
    },
    "fluoride": {
        "zh": "氟化物",
        "definition": "A substance that helps prevent dental caries and promotes remineralization.",
        "explanation_zh": "氟化物可以增强牙釉质抗酸能力，促进再矿化，是预防龋病的重要物质。",
        "category": "Preventive Dentistry",
    },
    "enamel": {
        "zh": "牙釉质",
        "definition": "The hard outer layer of the tooth crown.",
        "explanation_zh": "牙釉质是覆盖牙冠表面的最坚硬组织，主要作用是保护牙齿。",
        "category": "Dental Anatomy",
    },
    "dentin": {
        "zh": "牙本质",
        "definition": "The calcified tissue beneath enamel and cementum.",
        "explanation_zh": "牙本质位于牙釉质和牙骨质下方，构成牙齿主体，含有牙本质小管。",
        "category": "Dental Anatomy",
    },
    "cementum": {
        "zh": "牙骨质",
        "definition": "A calcified tissue covering the root surface of the tooth.",
        "explanation_zh": "牙骨质覆盖牙根表面，是牙周膜纤维附着的重要结构。",
        "category": "Dental Anatomy",
    },
    "pulp": {
        "zh": "牙髓",
        "definition": "The soft connective tissue inside the tooth containing nerves and blood vessels.",
        "explanation_zh": "牙髓是牙齿内部的软组织，含有神经、血管和结缔组织。",
        "category": "Dental Anatomy / Endodontics",
    },
    "pulp chamber": {
        "zh": "髓腔",
        "definition": "The central space in the crown of the tooth that contains dental pulp.",
        "explanation_zh": "髓腔是牙冠内部容纳牙髓的空间，与根管相连。",
        "category": "Dental Anatomy / Endodontics",
    },
    "root canal": {
        "zh": "根管",
        "definition": "The canal inside the tooth root that contains pulp tissue.",
        "explanation_zh": "根管位于牙根内部，含有牙髓组织，是根管治疗的主要处理部位。",
        "category": "Endodontics",
    },
    "root canal treatment": {
        "zh": "根管治疗",
        "definition": "A procedure to remove infected or inflamed pulp and seal the root canal system.",
        "explanation_zh": "根管治疗是去除感染或炎症牙髓、清理根管并进行充填封闭的治疗方法。",
        "category": "Endodontics",
    },
    "pulpitis": {
        "zh": "牙髓炎",
        "definition": "Inflammation of the dental pulp.",
        "explanation_zh": "牙髓炎是牙髓组织发生炎症，常由龋病、外伤或修复刺激引起。",
        "category": "Endodontics",
    },
    "reversible pulpitis": {
        "zh": "可复性牙髓炎",
        "definition": "Mild inflammation of the pulp that can recover if the irritant is removed.",
        "explanation_zh": "可复性牙髓炎通常疼痛短暂，去除刺激因素后牙髓有恢复可能。",
        "category": "Endodontics",
    },
    "irreversible pulpitis": {
        "zh": "不可复性牙髓炎",
        "definition": "Severe pulp inflammation that cannot return to normal and often requires endodontic treatment.",
        "explanation_zh": "不可复性牙髓炎常出现自发痛或刺激去除后疼痛持续，通常需要根管治疗。",
        "category": "Endodontics",
    },
    "periapical lesion": {
        "zh": "根尖周病变",
        "definition": "A pathological change around the apex of the tooth root.",
        "explanation_zh": "根尖周病变发生在牙根尖周围，常与牙髓感染扩散有关。",
        "category": "Endodontics / Oral Radiology",
    },
    "periapical periodontitis": {
        "zh": "根尖周炎",
        "definition": "Inflammation of tissues around the tooth root apex.",
        "explanation_zh": "根尖周炎是牙根尖周围组织的炎症，多由根管感染引起。",
        "category": "Endodontics",
    },
    "gingiva": {
        "zh": "牙龈",
        "definition": "The soft tissue surrounding the teeth and covering the alveolar bone.",
        "explanation_zh": "牙龈是包绕牙齿并覆盖牙槽骨的软组织，是牙周组织的一部分。",
        "category": "Periodontology",
    },
    "gingivitis": {
        "zh": "牙龈炎",
        "definition": "Inflammation of the gingiva without loss of periodontal attachment.",
        "explanation_zh": "牙龈炎是牙龈组织炎症，通常没有牙周附着丧失，是牙周病早期常见表现。",
        "category": "Periodontology",
    },
    "periodontitis": {
        "zh": "牙周炎",
        "definition": "Inflammation of the supporting tissues of the teeth with attachment loss.",
        "explanation_zh": "牙周炎是牙周支持组织炎症，伴有牙周附着丧失和牙槽骨吸收。",
        "category": "Periodontology",
    },
    "periodontal ligament": {
        "zh": "牙周膜",
        "definition": "A connective tissue structure between cementum and alveolar bone.",
        "explanation_zh": "牙周膜位于牙骨质和牙槽骨之间，具有支持、缓冲和感觉功能。",
        "category": "Periodontology / Dental Anatomy",
    },
    "alveolar bone": {
        "zh": "牙槽骨",
        "definition": "The bone that supports and surrounds the roots of the teeth.",
        "explanation_zh": "牙槽骨是支持并包绕牙根的骨组织，是牙周支持结构的重要组成部分。",
        "category": "Periodontology / Dental Anatomy",
    },
    "periodontal pocket": {
        "zh": "牙周袋",
        "definition": "A pathological deepening of the gingival sulcus.",
        "explanation_zh": "牙周袋是龈沟病理性加深的表现，常见于牙周炎。",
        "category": "Periodontology",
    },
    "attachment loss": {
        "zh": "附着丧失",
        "definition": "Loss of periodontal attachment between the tooth and supporting tissues.",
        "explanation_zh": "附着丧失表示牙周支持组织与牙齿之间的连接被破坏，是牙周炎的重要指标。",
        "category": "Periodontology",
    },
    "scaling": {
        "zh": "洁治",
        "definition": "Removal of plaque and calculus from tooth surfaces.",
        "explanation_zh": "洁治是去除牙面牙菌斑和牙结石的治疗方法，常用于牙周基础治疗。",
        "category": "Periodontology",
    },
    "root planing": {
        "zh": "根面平整",
        "definition": "Smoothing the root surface to remove calculus and contaminated cementum.",
        "explanation_zh": "根面平整是清除根面牙石和受污染牙骨质，使根面更平滑的牙周治疗方法。",
        "category": "Periodontology",
    },
    "occlusion": {
        "zh": "咬合",
        "definition": "The contact relationship between upper and lower teeth.",
        "explanation_zh": "咬合是上下牙接触时形成的关系，是修复、正畸和颞下颌关节相关内容的基础概念。",
        "category": "Occlusion",
    },
    "malocclusion": {
        "zh": "错颌畸形",
        "definition": "An abnormal relationship between the upper and lower teeth or jaws.",
        "explanation_zh": "错颌畸形是上下牙列或上下颌关系异常，常见于正畸学。",
        "category": "Orthodontics",
    },
    "overjet": {
        "zh": "覆盖",
        "definition": "The horizontal distance between upper and lower anterior teeth.",
        "explanation_zh": "覆盖是上下前牙之间的水平距离，是正畸检查的重要指标。",
        "category": "Orthodontics",
    },
    "overbite": {
        "zh": "覆合",
        "definition": "The vertical overlap of upper anterior teeth over lower anterior teeth.",
        "explanation_zh": "覆合是上前牙覆盖下前牙的垂直距离，过大或过小都可能属于异常咬合。",
        "category": "Orthodontics",
    },
    "crowding": {
        "zh": "牙列拥挤",
        "definition": "Insufficient space for proper alignment of teeth.",
        "explanation_zh": "牙列拥挤是牙弓空间不足导致牙齿排列不齐的情况。",
        "category": "Orthodontics",
    },
    "orthodontic appliance": {
        "zh": "正畸矫治器",
        "definition": "A device used to correct tooth position or jaw relationship.",
        "explanation_zh": "正畸矫治器用于移动牙齿或调整颌骨关系，包括固定矫治器和活动矫治器。",
        "category": "Orthodontics",
    },
    "extraction": {
        "zh": "拔牙",
        "definition": "Removal of a tooth from its socket.",
        "explanation_zh": "拔牙是将牙齿从牙槽窝中移除的口腔外科操作。",
        "category": "Oral Surgery",
    },
    "impacted tooth": {
        "zh": "阻生牙",
        "definition": "A tooth that fails to erupt properly into the dental arch.",
        "explanation_zh": "阻生牙是不能正常萌出到牙列中的牙齿，常见于第三磨牙。",
        "category": "Oral Surgery",
    },
    "third molar": {
        "zh": "第三磨牙",
        "definition": "The last molar tooth, commonly called the wisdom tooth.",
        "explanation_zh": "第三磨牙也叫智齿，常发生阻生、冠周炎或邻牙龋坏等问题。",
        "category": "Oral Surgery / Dental Anatomy",
    },
    "local anesthesia": {
        "zh": "局部麻醉",
        "definition": "A technique that blocks sensation in a specific area.",
        "explanation_zh": "局部麻醉通过阻断局部神经传导，使特定区域失去痛觉。",
        "category": "Oral Surgery / Anesthesia",
    },
    "inferior alveolar nerve": {
        "zh": "下牙槽神经",
        "definition": "A branch of the mandibular nerve that supplies mandibular teeth.",
        "explanation_zh": "下牙槽神经支配下颌牙齿感觉，是下颌阻滞麻醉的重要目标神经。",
        "category": "Oral Anatomy / Anesthesia",
    },
    "oral mucosa": {
        "zh": "口腔黏膜",
        "definition": "The mucous membrane lining the oral cavity.",
        "explanation_zh": "口腔黏膜是覆盖口腔内部表面的黏膜组织。",
        "category": "Oral Medicine",
    },
    "ulcer": {
        "zh": "溃疡",
        "definition": "A break or defect in the epithelial surface.",
        "explanation_zh": "溃疡是上皮表面连续性破坏，口腔中常表现为疼痛性黏膜损害。",
        "category": "Oral Medicine",
    },
    "leukoplakia": {
        "zh": "白斑",
        "definition": "A white patch or plaque of the oral mucosa that cannot be characterized as another disease.",
        "explanation_zh": "白斑是口腔黏膜上的白色斑块，不能被诊断为其他明确疾病，具有潜在恶变风险。",
        "category": "Oral Medicine / Oral Pathology",
    },
    "crown": {
        "zh": "牙冠 / 全冠修复体",
        "definition": "The visible part of a tooth or an artificial restoration covering a tooth.",
        "explanation_zh": "crown 可指天然牙冠，也可指覆盖牙体的全冠修复体，需要根据上下文判断。",
        "category": "Dental Anatomy / Prosthodontics",
    },
    "bridge": {
        "zh": "固定桥",
        "definition": "A fixed dental prosthesis used to replace one or more missing teeth.",
        "explanation_zh": "固定桥是用于修复缺失牙的固定修复体，通常依靠邻牙或种植体支持。",
        "category": "Prosthodontics",
    },
    "denture": {
        "zh": "义齿",
        "definition": "A removable or fixed prosthesis replacing missing teeth.",
        "explanation_zh": "义齿用于修复缺失牙，可分为活动义齿、固定义齿和种植支持义齿等。",
        "category": "Prosthodontics",
    },
    "implant": {
        "zh": "种植体",
        "definition": "A device placed into bone to support a dental prosthesis.",
        "explanation_zh": "种植体通常植入牙槽骨中，用于支持牙冠、固定桥或义齿。",
        "category": "Implant Dentistry",
    },
    "osseointegration": {
        "zh": "骨结合",
        "definition": "Direct structural and functional connection between bone and the implant surface.",
        "explanation_zh": "骨结合是骨组织与种植体表面形成直接稳定连接，是种植修复成功的基础。",
        "category": "Implant Dentistry",
    },
    "impression": {
        "zh": "印模",
        "definition": "A negative reproduction of oral structures.",
        "explanation_zh": "印模是口腔组织形态的阴模，用于制作模型和修复体。",
        "category": "Prosthodontics",
    },
    "occlusal surface": {
        "zh": "咬合面",
        "definition": "The chewing surface of posterior teeth.",
        "explanation_zh": "咬合面是后牙用于咀嚼接触的表面。",
        "category": "Dental Anatomy",
    },
    "composite resin": {
        "zh": "复合树脂",
        "definition": "A tooth-colored restorative material used for direct restorations.",
        "explanation_zh": "复合树脂是一种牙色修复材料，常用于充填龋洞和美学修复。",
        "category": "Dental Materials / Operative Dentistry",
    },
    "amalgam": {
        "zh": "银汞合金",
        "definition": "A dental restorative material made from a mixture of metals including mercury and silver alloy.",
        "explanation_zh": "银汞合金是一种传统牙体修复材料，机械性能较好，但美观性较差。",
        "category": "Dental Materials",
    },
    "glass ionomer cement": {
        "zh": "玻璃离子水门汀",
        "definition": "A restorative material that can release fluoride and bond to tooth structure.",
        "explanation_zh": "玻璃离子水门汀可释放氟，并能与牙体组织形成化学结合，常用于儿童牙科和根面修复。",
        "category": "Dental Materials",
    },
    "bonding agent": {
        "zh": "粘接剂",
        "definition": "A material used to bond restorative materials to tooth structure.",
        "explanation_zh": "粘接剂用于使复合树脂等修复材料与牙釉质或牙本质结合。",
        "category": "Dental Materials / Operative Dentistry",
    },
    "etching": {
        "zh": "酸蚀",
        "definition": "Application of acid to tooth structure to improve bonding.",
        "explanation_zh": "酸蚀通过处理牙面形成微机械固位结构，提高粘接效果。",
        "category": "Operative Dentistry",
    },
    "radiograph": {
        "zh": "X 线片 / 放射影像",
        "definition": "An image produced using X-rays.",
        "explanation_zh": "radiograph 指 X 线影像，在口腔中常用于诊断龋病、根尖病变、牙周骨吸收等。",
        "category": "Oral Radiology",
    },
    "bitewing radiograph": {
        "zh": "咬翼片",
        "definition": "A dental radiograph used to detect interproximal caries and assess alveolar bone levels.",
        "explanation_zh": "咬翼片常用于检查邻面龋和牙槽骨高度，是龋病和牙周评估的重要影像。",
        "category": "Oral Radiology",
    },
    "periapical radiograph": {
        "zh": "根尖片",
        "definition": "A radiograph showing the whole tooth and surrounding periapical tissues.",
        "explanation_zh": "根尖片可以显示整颗牙及根尖周组织，常用于根尖病变和根管治疗评估。",
        "category": "Oral Radiology",
    },
    "panoramic radiograph": {
        "zh": "全景片",
        "definition": "A radiograph showing both jaws and many oral structures in a single image.",
        "explanation_zh": "全景片可以显示上下颌、牙列、颞下颌关节等整体情况，常用于初步筛查。",
        "category": "Oral Radiology",
    },
    "abscess": {
        "zh": "脓肿",
        "definition": "A localized collection of pus caused by infection.",
        "explanation_zh": "脓肿是感染导致的局限性脓液聚集，口腔中可见根尖脓肿或牙周脓肿。",
        "category": "Oral Pathology / Infection",
    },
    "cellulitis": {
        "zh": "蜂窝织炎",
        "definition": "A diffuse spreading infection of soft tissues.",
        "explanation_zh": "蜂窝织炎是软组织弥散性感染，较脓肿更弥散，严重时需要及时处理。",
        "category": "Oral Surgery / Infection",
    },
    "inflammation": {
        "zh": "炎症",
        "definition": "A biological response of tissues to harmful stimuli.",
        "explanation_zh": "炎症是组织对损伤、感染或刺激产生的生物学反应，常表现为红、肿、热、痛和功能障碍。",
        "category": "General Pathology",
    },
    "infection": {
        "zh": "感染",
        "definition": "Invasion and multiplication of microorganisms in body tissues.",
        "explanation_zh": "感染是微生物侵入并在组织中繁殖，可引起炎症和组织损害。",
        "category": "Microbiology / Pathology",
    },
    "necrosis": {
        "zh": "坏死",
        "definition": "Death of cells or tissues due to injury or disease.",
        "explanation_zh": "坏死是细胞或组织因损伤、缺血或感染等原因发生死亡。",
        "category": "General Pathology",
    },
    "edema": {
        "zh": "水肿",
        "definition": "Abnormal accumulation of fluid in tissues.",
        "explanation_zh": "水肿是组织间隙液体异常增多，可出现在炎症或循环障碍中。",
        "category": "General Pathology",
    },
    "anesthesia": {
        "zh": "麻醉",
        "definition": "Loss of sensation, often produced by drugs.",
        "explanation_zh": "麻醉是通过药物或其他方法使感觉暂时消失，口腔治疗中常用局部麻醉。",
        "category": "Anesthesia",
    },
    "analgesia": {
        "zh": "镇痛",
        "definition": "Relief from pain without necessarily causing loss of consciousness.",
        "explanation_zh": "镇痛是减轻或消除疼痛，不一定伴随意识丧失。",
        "category": "Pharmacology / Anesthesia",
    },
    "antibiotic": {
        "zh": "抗生素",
        "definition": "A drug used to treat bacterial infections.",
        "explanation_zh": "抗生素用于治疗细菌感染，但需要合理使用，避免滥用和耐药。",
        "category": "Pharmacology",
    },
    "analgesic": {
        "zh": "镇痛药",
        "definition": "A drug used to relieve pain.",
        "explanation_zh": "镇痛药用于缓解疼痛，口腔临床常用于术后痛或炎症相关疼痛。",
        "category": "Pharmacology",
    },
    "temporomandibular joint": {
        "zh": "颞下颌关节",
        "definition": "The joint connecting the mandible to the temporal bone.",
        "explanation_zh": "颞下颌关节连接下颌骨和颞骨，参与张口、闭口和咀嚼运动。",
        "category": "Oral Anatomy / TMJ",
    },
    "mandible": {
        "zh": "下颌骨",
        "definition": "The lower jaw bone.",
        "explanation_zh": "下颌骨是下颌的骨性结构，承载下牙列，并参与颞下颌关节运动。",
        "category": "Oral Anatomy",
    },
    "maxilla": {
        "zh": "上颌骨",
        "definition": "The upper jaw bone.",
        "explanation_zh": "上颌骨构成上颌及部分面中部结构，承载上牙列。",
        "category": "Oral Anatomy",
    },
    "incisor": {
        "zh": "切牙",
        "definition": "An anterior tooth used for cutting food.",
        "explanation_zh": "切牙位于牙列前部，主要用于切割食物。",
        "category": "Dental Anatomy",
    },
    "canine": {
        "zh": "尖牙",
        "definition": "A pointed tooth located between incisors and premolars.",
        "explanation_zh": "尖牙位于切牙和前磨牙之间，牙根较长，对美观和咬合引导有重要作用。",
        "category": "Dental Anatomy",
    },
    "premolar": {
        "zh": "前磨牙",
        "definition": "A tooth located between the canine and molars.",
        "explanation_zh": "前磨牙位于尖牙和磨牙之间，兼具撕裂和研磨功能。",
        "category": "Dental Anatomy",
    },
    "molar": {
        "zh": "磨牙",
        "definition": "A posterior tooth used for grinding food.",
        "explanation_zh": "磨牙位于牙列后部，主要用于研磨食物。",
        "category": "Dental Anatomy",
    },
}